import {
  Category,
  Priority,
  ComplaintStatus,
  Complaint,
  ComplaintCluster,
  DashboardMetrics,
  CategoryMetric,
  CityMetric,
  DepartmentMetric,
  City,
  Department,
} from '../types';

export const fallbackCities: City[] = [
  { id: 'city-1', name: 'New Delhi', state: 'Delhi', country: 'India', lat: 28.6139, lng: 77.2090, created_at: '2026-01-01T00:00:00Z' },
  { id: 'city-2', name: 'Bengaluru', state: 'Karnataka', country: 'India', lat: 12.9716, lng: 77.5946, created_at: '2026-01-01T00:00:00Z' },
  { id: 'city-3', name: 'Mumbai', state: 'Maharashtra', country: 'India', lat: 19.0760, lng: 72.8777, created_at: '2026-01-01T00:00:00Z' },
  { id: 'city-4', name: 'Indore', state: 'Madhya Pradesh', country: 'India', lat: 22.7196, lng: 75.8577, created_at: '2026-01-01T00:00:00Z' },
  { id: 'city-5', name: 'Hyderabad', state: 'Telangana', country: 'India', lat: 17.3850, lng: 78.4867, created_at: '2026-01-01T00:00:00Z' },
];

export const fallbackDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Municipal Water Supply & Sewerage Board',
    code: 'DJB_WATER',
    city_id: 'city-1',
    category_mapping: [Category.WATER_SUPPLY, Category.DRAINAGE],
    head_officer: 'Er. Rajesh Verma (Chief Engineer)',
    contact_email: 'watersupply.control@civicflow.gov',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'Solid Waste Management & Sanitation Dept',
    code: 'MCD_SAN',
    city_id: 'city-1',
    category_mapping: [Category.WASTE_MANAGEMENT, Category.SANITATION],
    head_officer: 'Dr. Sunita Sharma (Director of SWM)',
    contact_email: 'sanitation.ops@civicflow.gov',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Public Works & Roads Engineering Division',
    code: 'PWD_ROADS',
    city_id: 'city-1',
    category_mapping: [Category.ROADS, Category.PUBLIC_INFRASTRUCTURE],
    head_officer: 'Er. Alok Mishra (Superintending Engineer)',
    contact_email: 'pwd.roads.delhi@civicflow.gov',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'State Electricity Distribution Corporation',
    code: 'DISCOM_ELEC',
    city_id: 'city-1',
    category_mapping: [Category.STREET_LIGHTING, Category.ELECTRICITY],
    head_officer: 'Er. Priya Nair (General Manager Distribution)',
    contact_email: 'discom.maintenance@civicflow.gov',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const fallbackComplaints: Complaint[] = [
  {
    id: 'CF-2026-00412',
    citizen_id: 'usr-cit-1',
    citizen_name: 'Rohan Sharma',
    citizen_email: 'rohan.sharma@example.com',
    citizen_phone: '+91 98101 23456',
    description: 'Major water main pipe ruptured near Rohini Sector 9 crossing. Massive water gushing on the road causing traffic halt and wastage.',
    original_language: 'English',
    normalized_text: 'Major water main pipe ruptured near Rohini Sector 9 crossing.',
    category: Category.WATER_SUPPLY,
    subcategory: 'Pipeline Burst / Leakage',
    priority: Priority.CRITICAL,
    severity_score: 0.94,
    city_id: 'city-1',
    city_name: 'New Delhi',
    location: 'Rohini Sector 9 Crossing, Outer Ring Rd',
    latitude: 28.7150,
    longitude: 77.1190,
    duration: '2 hours',
    department_id: 'dept-1',
    department_name: 'Municipal Water Supply & Sewerage Board',
    assigned_officer_id: 'off-101',
    assigned_officer_name: 'Er. Rajesh Verma',
    status: ComplaintStatus.IN_PROGRESS,
    ai_confidence: 0.96,
    suggested_action: 'Deploy emergency valve closure and pipeline repair squad immediately.',
    cluster_id: 'cl-delhi-water-01',
    sla_deadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
    timeline: [
      {
        id: 'tl-1',
        complaint_id: 'CF-2026-00412',
        old_status: ComplaintStatus.SUBMITTED,
        new_status: ComplaintStatus.CLASSIFIED,
        changed_by: 'CivicFlow AI Engine',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        comment: 'AI Classification: Water Supply (96% confidence). Critical priority due to road flooding risk.',
      },
      {
        id: 'tl-2',
        complaint_id: 'CF-2026-00412',
        old_status: ComplaintStatus.CLASSIFIED,
        new_status: ComplaintStatus.ROUTED,
        changed_by: 'CivicFlow Routing Engine',
        timestamp: new Date(Date.now() - 3600000 * 1.8).toISOString(),
        comment: 'Auto-routed to Municipal Water Supply & Sewerage Board. SLA Target: 6 hours.',
      },
      {
        id: 'tl-3',
        complaint_id: 'CF-2026-00412',
        old_status: ComplaintStatus.ROUTED,
        new_status: ComplaintStatus.IN_PROGRESS,
        changed_by: 'Er. Rajesh Verma',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        comment: 'Field maintenance crew dispatched with suction excavator.',
      },
    ],
    comments: [
      {
        id: 'c-1',
        complaint_id: 'CF-2026-00412',
        author_id: 'off-101',
        author_name: 'Er. Rajesh Verma',
        author_role: 'DEPARTMENT_ADMIN',
        text: 'Emergency crew has isolated the mainline valve. Repair team is on-site with replacement 24-inch ductile iron pipe.',
        created_at: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
  },
  {
    id: 'CF-2026-00413',
    citizen_id: 'usr-cit-2',
    citizen_name: 'Ananya Iyer',
    citizen_email: 'ananya.iyer@example.com',
    citizen_phone: '+91 98450 11223',
    description: 'Multiple open garbage piles accumulating near Karol Bagh vegetable market. Severe stench and stray animals gathering.',
    original_language: 'English',
    normalized_text: 'Multiple open garbage piles accumulating near Karol Bagh vegetable market.',
    category: Category.WASTE_MANAGEMENT,
    subcategory: 'Illegal Garbage Dump',
    priority: Priority.HIGH,
    severity_score: 0.81,
    city_id: 'city-1',
    city_name: 'New Delhi',
    location: 'Karol Bagh Market Gate 3',
    latitude: 28.6517,
    longitude: 77.1906,
    duration: '24 hours',
    department_id: 'dept-2',
    department_name: 'Solid Waste Management & Sanitation Dept',
    assigned_officer_id: 'off-103',
    assigned_officer_name: 'Dr. Sunita Sharma',
    status: ComplaintStatus.ASSIGNED,
    ai_confidence: 0.94,
    suggested_action: 'Dispatch compactor truck and sanitary inspector for clearance.',
    sla_deadline: new Date(Date.now() + 12 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'CF-2026-00414',
    citizen_id: 'usr-cit-1',
    citizen_name: 'Rohan Sharma',
    citizen_email: 'rohan.sharma@example.com',
    description: 'Deep dangerous pothole on fast lane near Saket Metro Station underpass. Several two-wheeler riders lost balance.',
    original_language: 'English',
    normalized_text: 'Deep dangerous pothole on fast lane near Saket Metro Station underpass.',
    category: Category.ROADS,
    subcategory: 'Deep Pothole',
    priority: Priority.CRITICAL,
    severity_score: 0.92,
    city_id: 'city-1',
    city_name: 'New Delhi',
    location: 'Saket Metro Underpass, South Delhi',
    latitude: 28.5245,
    longitude: 77.2066,
    duration: '3 days',
    department_id: 'dept-3',
    department_name: 'Public Works & Roads Engineering Division',
    assigned_officer_id: 'off-104',
    assigned_officer_name: 'Er. Alok Mishra',
    status: ComplaintStatus.IN_PROGRESS,
    ai_confidence: 0.97,
    suggested_action: 'Deploy cold-mix asphalt quick patch and warning barricades.',
    sla_deadline: new Date(Date.now() + 6 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'CF-2026-00415',
    citizen_id: 'usr-cit-3',
    citizen_name: 'Vikram Mehta',
    citizen_email: 'vikram.mehta@example.com',
    description: 'Streetlights not functioning along entire 1km stretch of Bellandur Outer Ring Road. Dark and unsafe for pedestrians.',
    original_language: 'English',
    normalized_text: 'Streetlights not functioning along entire 1km stretch of Bellandur Outer Ring Road.',
    category: Category.STREET_LIGHTING,
    subcategory: 'Phase Outage / Dark Corridor',
    priority: Priority.HIGH,
    severity_score: 0.78,
    city_id: 'city-2',
    city_name: 'Bengaluru',
    location: 'Bellandur Tech Corridor, ORR',
    latitude: 12.9304,
    longitude: 77.6784,
    duration: '2 nights',
    department_id: 'dept-4',
    department_name: 'State Electricity Distribution Corporation',
    assigned_officer_id: 'off-201',
    assigned_officer_name: 'Er. Suresh Gowda',
    status: ComplaintStatus.ASSIGNED,
    ai_confidence: 0.95,
    suggested_action: 'Dispatch feeder line technician to check transformer circuit breaker.',
    sla_deadline: new Date(Date.now() + 18 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const fallbackClusters: ComplaintCluster[] = [
  {
    id: 'cl-delhi-water-01',
    title: 'Major Water Supply Outage & Pipeline Burst Cluster',
    category: Category.WATER_SUPPLY,
    city_id: 'city-1',
    city_name: 'New Delhi',
    ward_id: 'ward-101',
    ward_name: 'Ward 14 - Rohini Sector 9',
    location: 'Rohini Sector 9 Crossing',
    latitude: 28.7150,
    longitude: 77.1190,
    complaint_count: 5,
    priority: Priority.CRITICAL,
    confidence: 0.94,
    status: 'ACTIVE',
    recommended_action: 'Emergency Zonal Water Cut & Heavy Pipeline Repair Unit Dispatch',
    member_complaint_ids: ['CF-2026-00412'],
    spike_percentage: 180,
    first_reported_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    last_reported_at: new Date(Date.now() - 1800000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const fallbackMetrics: DashboardMetrics = {
  total_complaints: 142,
  pending_complaints: 28,
  resolved_complaints: 96,
  in_progress_complaints: 18,
  critical_complaints: 4,
  high_priority_complaints: 14,
  average_resolution_hours: 18.5,
  ai_routed_percentage: 97,
  active_clusters: 3,
  today_new_complaints: 12,
};

export const fallbackCategories: CategoryMetric[] = [
  { category: Category.WATER_SUPPLY, display_name: 'Water Supply', count: 38, percentage: 27, critical_count: 2, avg_resolution_hours: 16, trend: 'up', growth_rate: 8.5 },
  { category: Category.ROADS, display_name: 'Roads & Infrastructure', count: 32, percentage: 23, critical_count: 2, avg_resolution_hours: 36, trend: 'stable', growth_rate: 4.2 },
  { category: Category.WASTE_MANAGEMENT, display_name: 'Solid Waste', count: 28, percentage: 20, critical_count: 0, avg_resolution_hours: 12, trend: 'stable', growth_rate: 3.1 },
  { category: Category.STREET_LIGHTING, display_name: 'Street Lighting', count: 22, percentage: 15, critical_count: 0, avg_resolution_hours: 24, trend: 'down', growth_rate: -2.4 },
  { category: Category.DRAINAGE, display_name: 'Drainage & Sewerage', count: 14, percentage: 10, critical_count: 0, avg_resolution_hours: 28, trend: 'up', growth_rate: 6.8 },
  { category: Category.ELECTRICITY, display_name: 'Electricity', count: 8, percentage: 5, critical_count: 0, avg_resolution_hours: 8, trend: 'stable', growth_rate: 1.2 },
];

export const fallbackCitiesData: CityMetric[] = [
  { city_id: 'city-1', city: 'New Delhi', total_complaints: 58, critical_complaints: 2, high_priority: 6, pending: 12, resolved: 42, resolution_rate: 0.72, top_category: Category.WATER_SUPPLY },
  { city_id: 'city-2', city: 'Bengaluru', total_complaints: 46, critical_complaints: 1, high_priority: 5, pending: 9, resolved: 34, resolution_rate: 0.74, top_category: Category.ROADS },
  { city_id: 'city-3', city: 'Mumbai', total_complaints: 38, critical_complaints: 1, high_priority: 3, pending: 7, resolved: 28, resolution_rate: 0.74, top_category: Category.DRAINAGE },
];

export const fallbackDepartmentsData: DepartmentMetric[] = [
  { department_id: 'dept-1', department_name: 'Municipal Water Supply', total_assigned: 38, in_progress: 6, resolved: 28, pending: 4, workload_percentage: 27, officers_count: 6 },
  { department_id: 'dept-2', department_name: 'Solid Waste Management', total_assigned: 28, in_progress: 4, resolved: 22, pending: 2, workload_percentage: 20, officers_count: 8 },
  { department_id: 'dept-3', department_name: 'Public Works & Roads', total_assigned: 32, in_progress: 5, resolved: 23, pending: 4, workload_percentage: 23, officers_count: 5 },
  { department_id: 'dept-4', department_name: 'Electricity Distribution', total_assigned: 22, in_progress: 3, resolved: 17, pending: 2, workload_percentage: 16, officers_count: 4 },
];
